import { CmsPage } from './cms';

export const INITIAL_CMS_PAGES: CmsPage[] = [
  {
    id: 'page-home',
    slug: 'home',
    title: 'Página de Inicio (Home)',
    description: 'Página principal de la tienda Web-to-Print con sliders, categorías, cotizadores y testimonios.',
    isSystemPage: true,
    isPublished: true,
    metaTitle: 'Fusión Gráfica W2P | Impresión Litográfica, Libros y Empaques en Colombia',
    metaDescription: 'Plataforma Web-to-Print en Colombia. Impresión litográfica offset, cotizador de libros y revistas, cajas plegadizas y envíos nacionales con chequeo CTP incluido.',
    metaKeywords: ['litografia colombia', 'impresion libros manizales', 'web to print colombia', 'cajas plegadizas', 'tarjetas de presentacion'],
    createdAt: '2026-01-15T00:00:00.000Z',
    updatedAt: '2026-08-25T00:00:00.000Z',
    blocks: [
      {
        id: 'blk-home-hero',
        type: 'HERO_BANNER',
        displayOrder: 1,
        isEnabled: true,
        bgStyle: 'dark',
        headline: 'Impresión Litográfica & Soluciones Web-To-Print en Colombia',
        subheadline: 'Automatiza tus pedidos litográficos, libros, revistas y empaques con chequeo técnico CTP 300 DPI incluido.',
        badgeText: 'Tecnología Offset & Digital 300 DPI',
        ctaText: 'Ver Papelería Comercial',
        ctaLink: '/categoria/papeleria-comercial',
        secondaryCtaText: 'Cotizar Libros & Revistas',
        secondaryCtaLink: '/cotizador-libros',
        backgroundImageUrl: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?q=80&w=2000&auto=format&fit=crop',
        alignment: 'left',
        height: 'standard',
        showTrustBadges: true,
      },
      {
        id: 'blk-home-cats',
        type: 'CATEGORY_GRID',
        displayOrder: 2,
        isEnabled: true,
        title: 'Explora Nuestras Líneas de Producción',
        subtitle: 'Cotiza y configura especificaciones de papel, tintas y acabados en tiempo real',
        columns: 4,
        showBadge: true,
        layoutVariant: 'cards',
      },
      {
        id: 'blk-home-valprops',
        type: 'VALUE_PROPOSITION',
        displayOrder: 3,
        isEnabled: true,
        bgStyle: 'slate-50',
        title: '¿Por qué elegir Fusión Comunicación Gráfica?',
        subtitle: 'Más de 15 años perfeccionando procesos litográficos para entregarte la más alta calidad del mercado',
        columns: 4,
        items: [
          {
            id: 'vp-1',
            icon: 'ShieldCheck',
            title: 'Pre-Vuelo Técnico CTP',
            description: 'Verificamos resolución a 300 DPI, sangrado de 3mm y perfiles de color CMYK antes de entrar a prensa.',
            highlightBadge: 'Garantía CTP',
          },
          {
            id: 'vp-2',
            icon: 'Truck',
            title: 'Despachos Nacionales',
            description: 'Envíos diarios asegurados a Bogotá, Medellín, Cali, Eje Cafetero y toda Colombia con guía en tiempo real.',
            highlightBadge: 'Envíos 24/48h',
          },
          {
            id: 'vp-3',
            icon: 'Award',
            title: 'Sustratos Certificados',
            description: 'Papeles Propalcote, Bond ecológico, EarthPact de caña de azúcar y cartones plegadizos certificados FSC.',
            highlightBadge: 'Eco-Friendly',
          },
          {
            id: 'vp-4',
            icon: 'Zap',
            title: 'Precios Escalonados B2B',
            description: 'Accede a tarifas preferenciales para agencias, diseñadores y distribuidores con descuentos por volumen.',
            highlightBadge: 'Portal Mayorista',
          },
        ],
      },
      {
        id: 'blk-home-featured',
        type: 'FEATURED_PRODUCTS',
        displayOrder: 4,
        isEnabled: true,
        title: 'Productos Más Cotizados de la Semana',
        subtitle: 'Precios actualizados con entrega rápida y opciones de personalización',
        limit: 8,
        viewAllLinkText: 'Ver Todo el Catálogo',
        viewAllUrl: '/categoria/todas',
      },
      {
        id: 'blk-home-quoter',
        type: 'EMBEDDED_QUOTER_CTA',
        displayOrder: 5,
        isEnabled: true,
        bgStyle: 'gradient-teal',
        quoterType: 'libros',
        title: 'Cotizador Editorial Automatizado de Libros & Revistas',
        subtitle: 'Calcula lomo milimétrico, pliegos optimizados y acabados de portada rústica o pasta dura en segundos.',
        highlightText: 'EXCLUSIVO WEB-TO-PRINT',
        buttonText: 'Abrir Cotizador de Libros (PRO)',
        buttonLink: '/cotizador-libros',
        featureBullets: [
          'Cálculo instantáneo de lomo según gramaje de páginas',
          'Encuadernación cosida al hilo, fresada PUR o grapa a caballo',
          'Muestras previas en prueba de color digital certificada',
          'Descuentos agresivos para tirajes editoriales e institucionales',
        ],
      },
      {
        id: 'blk-home-prepress',
        type: 'TECH_SPECS_PREPRESS',
        displayOrder: 6,
        isEnabled: true,
        title: 'Especificaciones Técnicas para Impresión Óptima',
        subtitle: 'Sigue estos parámetros para garantizar resultados nítidos y libres de reprocesos en prensa',
        downloadGuideUrl: '/guia-archivos',
        downloadGuideText: 'Ver Guía Completa de Pre-Prensa',
        specs: [
          {
            id: 'spec-1',
            title: 'Resolución de Imágenes',
            specification: 'Mínimo 300 DPI a tamaño real 100%',
            importance: 'CRITICO',
            detail: 'Evita imágenes de baja resolución tomadas de sitios web o redes sociales para evitar pixelado en CTP.',
          },
          {
            id: 'spec-2',
            title: 'Margen de Sangrado (Bleed)',
            specification: '3 mm por cada lado exterior',
            importance: 'CRITICO',
            detail: 'Los fondos e imágenes que lleguen al borde del papel deben sobresalir 3mm para permitir corte limpio de guillotina.',
          },
          {
            id: 'spec-3',
            title: 'Espacio de Color',
            specification: 'CMYK (FOGRA39 / GRACoL)',
            importance: 'RECOMENDADO',
            detail: 'Convierte todas las fotos y vectores de RGB a CMYK para evitar discrepancias de color en sustrato físico.',
          },
          {
            id: 'spec-4',
            title: 'Tipografías & Textos',
            specification: 'Convertir a Curvas / Trazos (Outlines)',
            importance: 'ESTANDAR',
            detail: 'Convierte textos a curvas en Illustrator o CorelDraw, o incrusta las fuentes en el PDF final.',
          },
        ],
      },
      {
        id: 'blk-home-testimonials',
        type: 'TESTIMONIALS',
        displayOrder: 7,
        isEnabled: true,
        bgStyle: 'slate-50',
        title: 'Lo Que Dicen Nuestros Clientes Litográficos',
        subtitle: 'Más de 1.200 empresas, editoriales y agencias confían en nuestra precisión y cumplimiento',
        items: [
          {
            id: 'test-1',
            author: 'Arq. Mateo Gómez',
            role: 'Director Editorial',
            company: 'Ediciones & Arte Andino',
            quote: 'Imprimimos más de 3.000 catálogos de arte con Fusión Gráfica. La fidelidad de color en los sustratos satinados y el cosido al hilo fue simplemente impecable.',
            rating: 5,
            city: 'Medellín, Antioquia',
          },
          {
            id: 'test-2',
            author: 'Carolina Valencia',
            role: 'Gerente de Mercadeo',
            company: 'Café Origen Caldense',
            quote: 'Nuestras cajas plegadizas con acabado soft-touch y estampado dorado aumentaron un 40% el valor percibido de nuestra línea de exportación. Entrega súper puntual.',
            rating: 5,
            city: 'Manizales, Caldas',
          },
          {
            id: 'test-3',
            author: 'Felipe Restrepo',
            role: 'Líder Creativo',
            company: 'Agencia BrandStudio',
            quote: 'Como agencia B2B, el portal mayorista nos permite cotizar carpetas corporativas y volantes en 30 segundos y despachar con empaque anónimo directo a nuestros clientes.',
            rating: 5,
            city: 'Bogotá D.C.',
          },
        ],
      },
      {
        id: 'blk-home-partner',
        type: 'PARTNER_SHOWCASE',
        displayOrder: 8,
        isEnabled: true,
        partnerName: 'Atrio Agencia S.A.S',
        partnerTagline: 'Aliado Estratégico en Transformación Digital & Publicidad 360°',
        partnerLogoUrl: '',
        description: 'Potenciamos la presencia de tu marca conectando la mejor producción gráfica impresa con estrategias digitales de alto rendimiento.',
        services: [
          { title: 'Branding & Identidad Visual', desc: 'Diseño de manuales de marca, empaques y conceptos visuales de vanguardia.' },
          { title: 'Comercio Electrónico & Web', desc: 'Desarrollo de tiendas online, aplicaciones a medida y portales corporativos.' },
          { title: 'Marketing Omnicanal', desc: 'Pauta digital en Google y Meta, embudos de conversión y automatización de ventas.' },
        ],
        ctaText: 'Conocer Alianza Atrio Agencia',
        ctaLink: '/alianza-atrio',
      },
      {
        id: 'blk-home-faq',
        type: 'FAQ_ACCORDION',
        displayOrder: 9,
        isEnabled: true,
        title: 'Preguntas Frecuentes sobre Pedidos Web-To-Print',
        subtitle: 'Resolvemos tus inquietudes sobre tiempos de entrega, formas de pago y preparación de archivos',
        enableSearch: true,
        contactPromptText: '¿Tienes una solicitud técnica especial? Escríbenos directamente por WhatsApp.',
        items: [
          {
            id: 'faq-1',
            question: '¿Qué es el chequeo Pre-Vuelo y tiene algún costo adicional?',
            answer: 'El Pre-Vuelo es una revisión técnica exhaustiva que realizamos a tu archivo para asegurar que cumpla con resolución a 300 DPI, márgenes de corte y modo de color CMYK. En Fusión Gráfica este servicio está 100% incluido sin costo en todos los pedidos.',
            category: 'Archivos',
          },
          {
            id: 'faq-2',
            question: '¿Cuáles son los tiempos promedio de producción y despacho?',
            answer: 'La papelería estándar y gran formato se produce en 24 a 48 horas hábiles. Trabajos editoriales de libros y cajas plegadizas con troquel especial tardan entre 3 a 5 días hábiles. Los despachos se realizan con guía rastreable a toda Colombia.',
            category: 'Envíos',
          },
          {
            id: 'faq-3',
            question: '¿Cómo puedo acceder a precios de distribuidor o mayorista B2B?',
            answer: 'Si eres agencia de publicidad, diseñador freelance, empresa de eventos o litografía, puedes solicitar tu cuenta B2B en nuestra sección "Portal B2B". Tras validar tus datos, obtendrás descuentos automáticos del 20% al 45% y crédito rotativo.',
            category: 'B2B',
          },
          {
            id: 'faq-4',
            question: '¿Qué medios de pago aceptan?',
            answer: 'Aceptamos todas las tarjetas de crédito, PSE, transferencias Bancolombia / Davivienda, Nequi, Daviplata y pago contraentrega en Manizales.',
            category: 'Pagos',
          },
        ],
      },
    ],
  },
  {
    id: 'page-nosotros',
    slug: 'nosotros',
    title: 'Quiénes Somos & Trayectoria',
    description: 'Página institucional con la historia, valores y equipo de Fusión Comunicación Gráfica.',
    isSystemPage: true,
    isPublished: true,
    metaTitle: 'Quiénes Somos | Fusión Comunicación Gráfica Manizales Colombia',
    metaDescription: 'Conoce la historia, infraestructura litográfica y equipo humano detrás de Fusión Comunicación Gráfica. Innovación y calidad en impresión litográfica.',
    metaKeywords: ['litografia manizales', 'quienes somos fusion grafica', 'empresa litografica caldas', 'historia litografia'],
    createdAt: '2026-01-20T00:00:00.000Z',
    updatedAt: '2026-08-25T00:00:00.000Z',
    blocks: [
      {
        id: 'blk-nos-hero',
        type: 'HERO_BANNER',
        displayOrder: 1,
        isEnabled: true,
        bgStyle: 'gradient-dark',
        headline: 'Más de 15 años de Pasión, Precisión e Innovación Litográfica',
        subheadline: 'Combinamos la tradición del offset de alta fidelidad con la agilidad de la tecnología digital Web-to-Print en Colombia.',
        badgeText: 'Nuestra Historia & Filosofía',
        ctaText: 'Ver Nuestra Tecnología',
        ctaLink: '/tecnologia',
        secondaryCtaText: 'Hablar con un Asesor',
        secondaryCtaLink: 'https://wa.me/573243917169',
        alignment: 'center',
        height: 'compact',
      },
      {
        id: 'blk-nos-story',
        type: 'RICH_TEXT_MEDIA',
        displayOrder: 2,
        isEnabled: true,
        title: 'Nacidos en el Eje Cafetero, con Cobertura a Nivel Nacional',
        badge: 'TRAYECTORIA',
        mediaType: 'image',
        mediaUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?q=80&w=1200&auto=format&fit=crop',
        mediaPosition: 'right',
        contentHtml: `<p class="mb-4">Fundada en el corazón de Manizales, <strong>Fusión Comunicación Gráfica</strong> nació con una misión clara: democratizar el acceso a la impresión litográfica industrial con los más altos estándares de calidad internacional y tiempos de respuesta ágiles.</p><p class="mb-4">A lo largo de más de una década y media, hemos evolucionado de un taller litográfico tradicional a un ecosistema integral <strong>Web-to-Print</strong>, integrando pre-prensa digital CTP, prensas offset Heidelberg multicolor, acabados UV automatizados y una plataforma en la nube que permite a clientes de toda Colombia cotizar y ordenar en segundos.</p>`,
        checklistItems: [
          'Capacidad de producción de más de 500.000 pliegos mensuales',
          'Taller de encuadernación rústica PUR y acabados de lujo integrado',
          'Compromiso 100% con sustratos de fuentes sostenibles FSC y tintas vegetales',
          'Alianza estratégica con Atrio Agencia S.A.S para soluciones digitales 360°',
        ],
      },
      {
        id: 'blk-nos-values',
        type: 'VALUE_PROPOSITION',
        displayOrder: 3,
        isEnabled: true,
        bgStyle: 'slate-50',
        title: 'Los Pilares que Guían Nuestro Trabajo',
        subtitle: 'Cada trabajo impreso que sale de nuestra planta refleja nuestro compromiso ético y técnico',
        columns: 3,
        items: [
          {
            id: 'v-1',
            icon: 'ShieldCheck',
            title: 'Obsesión por el Color',
            description: 'Estandarización bajo normas ISO 12647 y perfiles Fogra para asegurar que los colores de tu marca se reproduzcan con exactitud milimétrica.',
          },
          {
            id: 'v-2',
            icon: 'Clock',
            title: 'Puntualidad Inquebrantable',
            description: 'Sabemos que tus eventos, lanzamientos y campañas no admiten retrasos. Respetamos los cronogramas de despacho pactados.',
          },
          {
            id: 'v-3',
            icon: 'Sparkles',
            title: 'Innovación Constante',
            description: 'Actualizamos permanentemente nuestros procesos con software de imposición inteligente y cotizadores algorítmicos.',
          },
        ],
      },
      {
        id: 'blk-nos-contact',
        type: 'CONTACT_MAP_FORM',
        displayOrder: 4,
        isEnabled: true,
        title: 'Visita Nuestras Instalaciones o Contáctanos',
        subtitle: 'Estamos ubicados en el centro de Manizales, listos para atender tus requerimientos corporativos.',
        email: 'comercial@fusioncg.com',
        phone: '+57 324 3917169',
        whatsappNumber: '573243917169',
        address: 'Cra. 22 #24 - 47, Centro, Manizales, Caldas, Colombia',
        scheduleText: 'Lunes a Viernes: 8:00 AM - 6:00 PM | Sábados: 8:30 AM - 1:00 PM',
        showForm: true,
        showMap: true,
      },
    ],
  },
  {
    id: 'page-tecnologia',
    slug: 'tecnologia',
    title: 'Nuestra Tecnología & Parque de Maquinaria',
    description: 'Detalle de prensas offset, CTP directo a plancha, plotters digitales y acabados de lujo.',
    isSystemPage: true,
    isPublished: true,
    metaTitle: 'Tecnología Litográfica & Maquinaria Offset | Fusión Gráfica',
    metaDescription: 'Descubre nuestra infraestructura tecnológica en Manizales: Prensas Heidelberg, CTP Térmico Agfa, barniz UV, laminado Soft-Touch y encuadernación PUR.',
    metaKeywords: ['maquinaria litografica', 'prensas offset heidelberg', 'ctp termico colombia', 'acabados uv soft touch'],
    createdAt: '2026-01-22T00:00:00.000Z',
    updatedAt: '2026-08-25T00:00:00.000Z',
    blocks: [
      {
        id: 'blk-tec-hero',
        type: 'HERO_BANNER',
        displayOrder: 1,
        isEnabled: true,
        bgStyle: 'dark',
        headline: 'Ingeniería Litográfica de Vanguardia & Precisión de Impresión',
        subheadline: 'Equipamiento industrial de última generación para entregarte definición fotográfica y acabados de lujo en cada tiraje.',
        badgeText: 'Prensas Offset, CTP & Acabados',
        ctaText: 'Cotizar con Nosotros',
        ctaLink: '/cotizador-libros',
        alignment: 'center',
        height: 'compact',
      },
      {
        id: 'blk-tec-ctp',
        type: 'RICH_TEXT_MEDIA',
        displayOrder: 2,
        isEnabled: true,
        title: 'Pre-prensa Directa a Plancha (CTP Térmico Agfa)',
        badge: 'RESOLUCIÓN FOTOGRÁFICA',
        mediaType: 'image',
        mediaUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=1200&auto=format&fit=crop',
        mediaPosition: 'left',
        contentHtml: `<p class="mb-4">Eliminamos por completo las películas intermedias y los errores de registro analógicos. Nuestro sistema <strong>Computer to Plate (CTP) Térmico de alta resolución</strong> graba planchas de aluminio a 2400 DPI con tramado estocástico de última generación.</p><p>Esto garantiza puntos de trama nítidos desde el 1% hasta el 99%, degradados perfectamente continuos y texto tipográfico ultra-delgado sin empaste.</p>`,
        checklistItems: [
          'Resolución de grabado de 2400 DPI',
          'Calibración densitométrica y curvas de compensación de ganancia de punto',
          'Química ecológica de bajo impacto ambiental',
          'Registro óptico de alta precisión para cuadricromía y tintas Pantone',
        ],
      },
      {
        id: 'blk-tec-offset',
        type: 'RICH_TEXT_MEDIA',
        displayOrder: 3,
        isEnabled: true,
        bgStyle: 'slate-50',
        title: 'Prensas Offset Heidelberg Multicolor',
        badge: 'ALTA PRODUCCIÓN INDUSTRIAL',
        mediaType: 'image',
        mediaUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?q=80&w=1200&auto=format&fit=crop',
        mediaPosition: 'right',
        contentHtml: `<p class="mb-4">Nuestra línea de prensas Heidelberg está diseñada para brindar estabilidad cromática a altas velocidades de hasta 15.000 pliegos por hora. Con entintado continuo computarizado y control de balance agua-tinta automático, logramos una homogeneidad de color idéntica desde el primer hasta el último pliego del tiraje.</p>`,
        checklistItems: [
          'Soporte de pliegos desde tamaño cuarto hasta pliego completo',
          'Impresión sobre papeles desde 60g hasta cartulinas de 450g',
          'Unidad de barniz de protección en línea para secado ultrarrápido',
          'Capacidad para 5 colores simultáneos (CMYK + Tinta Especial o Pantone)',
        ],
      },
      {
        id: 'blk-tec-finishes',
        type: 'VALUE_PROPOSITION',
        displayOrder: 4,
        isEnabled: true,
        title: 'Taller Especializado de Acabados & Transformación',
        subtitle: 'El valor de un impreso se define en el detalle. Dale a tus empaques y portadas un toque exclusivo.',
        columns: 4,
        items: [
          {
            id: 'tf-1',
            icon: 'Sparkles',
            title: 'Plastificado Soft-Touch',
            description: 'Laminado mate con tacto aterciopelado de alta resistencia al rayado y repelencia a huellas dactilares.',
            highlightBadge: 'Gama Premium',
          },
          {
            id: 'tf-2',
            icon: 'Layers',
            title: 'Reserva UV Brillante',
            description: 'Barniz sectorizado con brillo espejo que resalta logotipos, texturas y elementos clave sobre fondos mates.',
            highlightBadge: 'Alto Contraste',
          },
          {
            id: 'tf-3',
            icon: 'Award',
            title: 'Estampado Foil Metálico',
            description: 'Aplicación térmica de películas metálicas oro, plata, cobre y holográficas de impacto visual.',
            highlightBadge: 'Hot Stamping',
          },
          {
            id: 'tf-4',
            icon: 'Printer',
            title: 'Encuadernación PUR & Tapa Dura',
            description: 'Adhesivo reactivo de poliuretano (PUR) que asegura apertura de 180° y durabilidad por décadas.',
            highlightBadge: 'Editorial PRO',
          },
        ],
      },
    ],
  },
  {
    id: 'page-guia-archivos',
    slug: 'guia-archivos',
    title: 'Guía Técnica de Pre-Prensa y Archivos',
    description: 'Manual paso a paso para diseñadores gráficos sobre preparación de PDFs para imprenta.',
    isSystemPage: true,
    isPublished: true,
    metaTitle: 'Guía de Preparación de Archivos para Imprenta | Fusión Gráfica',
    metaDescription: 'Aprende a preparar tus artes para litografía: sangrado 3mm, perfiles CMYK, resolución 300 DPI, tipografías a curvas y troqueles.',
    metaKeywords: ['guia preprensa', 'como preparar archivos para impresion', 'sangrado de impresion', 'cmyk vs rgb imprenta'],
    createdAt: '2026-01-25T00:00:00.000Z',
    updatedAt: '2026-08-25T00:00:00.000Z',
    blocks: [
      {
        id: 'blk-guia-hero',
        type: 'HERO_BANNER',
        displayOrder: 1,
        isEnabled: true,
        bgStyle: 'gradient-teal',
        headline: 'Guía Técnica de Preparación de Archivos para Impresión Litográfica',
        subheadline: 'Sigue estas pautas para que tus diseños salgan de prensa exactamente como los imaginaste en pantalla.',
        badgeText: 'Manual de Pre-Prensa para Diseñadores',
        ctaText: 'Descargar Plantillas PDF',
        ctaLink: '/categoria/papeleria-comercial',
        alignment: 'left',
        height: 'compact',
      },
      {
        id: 'blk-guia-specs',
        type: 'TECH_SPECS_PREPRESS',
        displayOrder: 2,
        isEnabled: true,
        title: 'Los 6 Requisitos Obligatorios de Pre-Vuelo',
        subtitle: 'Nuestros sistemas automáticos CTP validan estos parámetros antes de la filmación de planchas',
        specs: [
          {
            id: 'g-1',
            title: '1. Formato de Entrega del Archivo',
            specification: 'PDF/X-1a:2001 o PDF/X-4 de Alta Calidad',
            importance: 'CRITICO',
            detail: 'Exporta siempre como PDF de imprenta. No envíes capturas de pantalla, archivos JPG comprimidos ni documentos de Word/PowerPoint.',
          },
          {
            id: 'g-2',
            title: '2. Sangrado (Bleed) y Margen de Seguridad',
            specification: '3 mm de sangrado exterior | 4 mm de margen interno',
            importance: 'CRITICO',
            detail: 'Extiende fondos y elementos que toquen el borde 3mm hacia afuera. Mantén textos y logotipos a mínimo 4mm del borde de corte.',
          },
          {
            id: 'g-3',
            title: '3. Modo y Espacio de Color',
            specification: 'CMYK estricto (Evitar RGB y LAB)',
            importance: 'CRITICO',
            detail: 'Los colores RGB lucen brillantes en pantalla gracias a la luz emitida, pero en papel se imprimen con pigmentos CMYK. Convierte antes de exportar.',
          },
          {
            id: 'g-4',
            title: '4. Conversión de Tipografías',
            specification: 'Convertir a Trazos / Curvas (Outlines)',
            importance: 'RECOMENDADO',
            detail: 'En Illustrator (Ctrl+Shift+O / Cmd+Shift+O) o InDesign, convierte todas las tipografías a curvas para evitar sustituciones accidentales de fuentes.',
          },
          {
            id: 'g-5',
            title: '5. Negro Puro vs Negro Enriquecido',
            specification: 'Textos pequeños: C0 M0 Y0 K100 | Fondos: C40 M30 Y20 K100',
            importance: 'RECOMENDADO',
            detail: 'Para textos finos menores a 12pt usa solo 100% Negro (K). Para fondos negros grandes y profundos usa negro enriquecido.',
          },
          {
            id: 'g-6',
            title: '6. Capas de Troquel y Reserva UV',
            specification: 'Tintas Planas (Spot Color) en capas separadas',
            importance: 'ESTANDAR',
            detail: 'Dibuja las líneas de troquel en una capa independiente con un color de tinta plana nombrado "Troquel" y configurado en Sobreimprimir (Overprint).',
          },
        ],
      },
      {
        id: 'blk-guia-faq',
        type: 'FAQ_ACCORDION',
        displayOrder: 3,
        isEnabled: true,
        bgStyle: 'slate-50',
        title: 'Preguntas Frecuentes sobre Archivos y Corrección de Color',
        subtitle: 'Respuestas a los problemas más habituales reportados en el departamento de pre-prensa',
        items: [
          {
            id: 'gf-1',
            question: '¿Por qué mi azul se imprimió morado?',
            answer: 'En impresión CMYK, cuando el porcentaje de Magenta supera el 70% del valor de Cyan, el azul vira hacia tonos púrpuras o violetas. Para un azul intenso y limpio, mantén siempre una diferencia de mínimo 30% a 40% entre Cyan y Magenta (por ej: C:100 M:65 Y:0 K:10).',
            category: 'Color',
          },
          {
            id: 'gf-2',
            question: '¿Puedo enviar archivos en Canva o Photoshop?',
            answer: 'Sí. En Canva, asegúrate de descargar en "PDF para Impresión" marcando la casilla "Marcas de corte y sangría" y seleccionando perfil de color CMYK. En Photoshop, crea tu lienzo a 300 DPI y añade 6mm extra de ancho y alto para el sangrado total.',
            category: 'Software',
          },
          {
            id: 'gf-3',
            question: '¿Qué pasa si mi archivo tiene errores y ya pagué la orden?',
            answer: 'Nuestro equipo de pre-prensa te notificará inmediatamente vía correo y WhatsApp indicando el error detectado y te dará la opción de reenviar el archivo corregido sin ningún costo adicional.',
            category: 'Proceso',
          },
        ],
      },
    ],
  },
  {
    id: 'page-alianza-atrio',
    slug: 'alianza-atrio',
    title: 'Alianza Estratégica con Atrio Agencia S.A.S',
    description: 'Información sobre nuestra alianza con Atrio Agencia para proyectos de transformación digital y marketing.',
    isSystemPage: true,
    isPublished: true,
    metaTitle: 'Alianza Estratégica | Fusión Gráfica & Atrio Agencia S.A.S',
    metaDescription: 'La combinación perfecta entre producción gráfica litográfica de alta gama y soluciones integrales de marketing digital y desarrollo web con Atrio Agencia.',
    metaKeywords: ['atrio agencia sas', 'alianza digital manizales', 'marketing y litografia', 'agencia de publicidad 360'],
    createdAt: '2026-02-01T00:00:00.000Z',
    updatedAt: '2026-08-25T00:00:00.000Z',
    blocks: [
      {
        id: 'blk-atr-hero',
        type: 'HERO_BANNER',
        displayOrder: 1,
        isEnabled: true,
        bgStyle: 'gradient-dark',
        headline: 'Sinergia 360°: Producción Litográfica & Estrategia Digital',
        subheadline: 'Fusión Comunicación Gráfica y Atrio Agencia S.A.S se unen para ofrecer a tu empresa soluciones integradas de marca, desde el diseño y software hasta el empaque físico.',
        badgeText: 'Alianza Estratégica Corporativa',
        ctaText: 'Solicitar Consultoría 360°',
        ctaLink: 'https://wa.me/573243917169?text=Hola,%20deseo%20información%20sobre%20los%20servicios%20de%20la%20Alianza%20Atrio%20+%20Fusión',
        secondaryCtaText: 'Ver Servicios',
        secondaryCtaLink: '#servicios',
        alignment: 'center',
        height: 'standard',
      },
      {
        id: 'blk-atr-showcase',
        type: 'PARTNER_SHOWCASE',
        displayOrder: 2,
        isEnabled: true,
        partnerName: 'Atrio Agencia S.A.S',
        partnerTagline: 'Consultoría en Marcas, Plataformas Web y Expansión Comercial',
        description: 'Una agencia de innovación digital y diseño estratégico con base en Colombia, especializada en ayudar a marcas a escalar mediante tecnología, diseño centrado en el usuario y pauta publicitaria medible.',
        services: [
          { title: 'Identidad Corporativa & Empaque', desc: 'Diseño estructural de cajas, arquitectura de marca y sistemas visuales de alta categoría.' },
          { title: 'Desarrollo de Software & E-Commerce', desc: 'Portales transaccionales, cotizadores a la medida y automatización de procesos empresariales.' },
          { title: 'Generación de Demanda & Pauta Digital', desc: 'Campañas de adquisición de clientes en Google Ads, Meta Ads y posicionamiento orgánico SEO.' },
          { title: 'Producción Audiovisual & Contenido', desc: 'Fotografía publicitaria de producto, video comercial 4K y animación 3D.' },
        ],
        ctaText: 'Visitar Sitio Web de Atrio Agencia',
        ctaLink: 'https://atrioagencia.com',
      },
      {
        id: 'blk-atr-values',
        type: 'VALUE_PROPOSITION',
        displayOrder: 3,
        isEnabled: true,
        bgStyle: 'slate-50',
        title: 'Ventajas de un Proveedor Único para tu Marca',
        subtitle: 'Evita discrepancias entre lo que diseña la agencia y lo que la imprenta puede producir en máquina',
        columns: 3,
        items: [
          {
            id: 'av-1',
            icon: 'Zap',
            title: 'Cero Fricción de Pre-Prensa',
            description: 'Los artes nacen diseñados conociendo exactamente las capacidades de nuestras prensas y troqueles, reduciendo tiempos a la mitad.',
          },
          {
            id: 'av-2',
            icon: 'DollarSign',
            title: 'Tarifas de Paquete Integrado',
            description: 'Obtén descuentos significativos al contratar servicios de diseño estratégico y producción física bajo el mismo convenio.',
          },
          {
            id: 'av-3',
            icon: 'Award',
            title: 'Coherencia de Marca Total',
            description: 'El mismo estándar estético en tu página web, tus redes sociales y tus catálogos impresos en papel de alta gama.',
          },
        ],
      },
    ],
  },
  {
    id: 'page-mayoristas',
    slug: 'mayoristas',
    title: 'Portal de Mayoristas B2B & Distribuidores',
    description: 'Landing comercial para agencias de publicidad, revendedores e imprentas con beneficios por volumen.',
    isSystemPage: true,
    isPublished: true,
    metaTitle: 'Programa de Distribuidores Litográficos B2B | Fusión Gráfica',
    metaDescription: 'Únete a la red de distribuidores de Fusión Gráfica: precios de fábrica, empaques marca blanca y crédito rotativo para agencias.',
    metaKeywords: ['distribuidores litografia', 'impresion marca blanca', 'litografia para agencias b2b', 'precios mayoristas impresion'],
    createdAt: '2026-02-05T00:00:00.000Z',
    updatedAt: '2026-08-25T00:00:00.000Z',
    blocks: [
      {
        id: 'blk-may-hero',
        type: 'HERO_BANNER',
        displayOrder: 1,
        isEnabled: true,
        bgStyle: 'dark',
        headline: 'Tu Planta de Producción Litográfica Marca Blanca en Colombia',
        subheadline: 'El aliado invisible de más de 400 agencias de publicidad y diseñadores independientes. Precios de fábrica y despachos directos a tu cliente final.',
        badgeText: 'Programa Exclusivo para Profesionales de las Artes Gráficas',
        ctaText: 'Solicitar Registro B2B',
        ctaLink: '/b2b',
        secondaryCtaText: 'Conocer Beneficios',
        secondaryCtaLink: '#beneficios',
        alignment: 'left',
        height: 'standard',
      },
      {
        id: 'blk-may-benefits',
        type: 'VALUE_PROPOSITION',
        displayOrder: 2,
        isEnabled: true,
        bgStyle: 'white',
        title: 'Beneficios Exclusivos del Canal B2B',
        subtitle: 'Diseñado para maximizar el margen de ganancia de tu agencia sin necesidad de invertir en maquinaria',
        columns: 4,
        items: [
          {
            id: 'mb-1',
            icon: 'DollarSign',
            title: 'Descuentos del 20% al 45%',
            description: 'Margen de reventa garantizado con precios de escala industrial en todos los productos del catálogo.',
            highlightBadge: 'Tarifa Dealer',
          },
          {
            id: 'mb-2',
            icon: 'Truck',
            title: 'Envíos con Marca Blanca',
            description: 'Empacamos de forma neutra y despachamos a nombre de tu agencia directamente a tu cliente final.',
            highlightBadge: '100% Anónimo',
          },
          {
            id: 'mb-3',
            icon: 'Clock',
            title: 'Prioridad de Producción',
            description: 'Cola de producción preferente en prensas y guillotinas con chequeo técnico prioritario.',
            highlightBadge: 'Línea Rápida',
          },
          {
            id: 'mb-4',
            icon: 'ShieldCheck',
            title: 'Línea de Crédito Rotativo',
            description: 'Facturación quincenal o mensual a 30 días para clientes corporativos calificados.',
            highlightBadge: 'Crédito B2B',
          },
        ],
      },
      {
        id: 'blk-may-cta',
        type: 'EMBEDDED_QUOTER_CTA',
        displayOrder: 3,
        isEnabled: true,
        bgStyle: 'gradient-teal',
        quoterType: 'general',
        title: '¿Listo para empezar a ganar más con tus proyectos impresos?',
        subtitle: 'Completa tu solicitud en 2 minutos. Nuestro equipo comercial aprobará tu cuenta en menos de 2 horas hábiles.',
        buttonText: 'Ir al Portal B2B Mayoristas',
        buttonLink: '/b2b',
        featureBullets: [
          'Sin cuota de membresía ni permanencia mínima',
          'Acceso inmediato a cotizaciones con descuento aplicado',
          'Soporte directo con un ejecutivo de cuenta litográfico asignado',
        ],
      },
    ],
  },
];
