import { z } from 'zod';
import type { Permission } from '../auth/permissions';

export type WidgetCategory =
  | 'PERSONAL'
  | 'COMERCIAL'
  | 'PRODUCCION'
  | 'FINANCIERO'
  | 'EQUIPO'
  | 'SISTEMA';

export type WidgetSize = 'SMALL' | 'MEDIUM' | 'LARGE' | 'FULL';

export type WidgetDataSource = 'METRIC_DAILY' | 'METRIC_MONTHLY' | 'LIVE_LIGHT';

export interface WidgetDefinition {
  key: string; // identificador estable, nunca cambia
  title: string; // en español
  description: string; // qué responde, en una frase
  category: WidgetCategory;
  requiredPermissions: Permission[];
  suggestedRoles: string[];
  defaultSize: WidgetSize;
  mobileFallbackKey?: string; // versión resumida para móvil
  refreshSeconds: number; // 0 = solo al cargar
  dataSource: WidgetDataSource;
  configSchema: z.ZodTypeAny;
  drillDownRoute: (config?: any) => string;
  availableFrom: string; // sub-etapa o etapa que lo habilita
}

const EmptyConfigSchema = z.object({}).optional().default({});

export const WIDGET_CATALOG: Record<string, WidgetDefinition> = {
  // ==========================================================================
  // PERSONALES (Para todos los roles)
  // ==========================================================================
  mi_dia: {
    key: 'mi_dia',
    title: 'Mi Día',
    description: 'Tareas de hoy, vencidas y próxima cita, con cierre de tarea en un clic.',
    category: 'PERSONAL',
    requiredPermissions: ['home:read'],
    suggestedRoles: ['admin', 'comercial', 'produccion', 'planta', 'gerencia'],
    defaultSize: 'MEDIUM',
    refreshSeconds: 60,
    dataSource: 'LIVE_LIGHT',
    configSchema: EmptyConfigSchema,
    drillDownRoute: () => '/dashboard/comercial/agenda',
    availableFrom: '15.2',
  },
  mis_tareas_resumen: {
    key: 'mis_tareas_resumen',
    title: 'Resumen de Mis Tareas',
    description: 'Pendientes distribuidos por prioridad y fecha de vencimiento.',
    category: 'PERSONAL',
    requiredPermissions: ['home:read'],
    suggestedRoles: ['admin', 'comercial', 'produccion', 'planta', 'gerencia'],
    defaultSize: 'SMALL',
    refreshSeconds: 60,
    dataSource: 'LIVE_LIGHT',
    configSchema: EmptyConfigSchema,
    drillDownRoute: () => '/mi-rendimiento',
    availableFrom: '15.2',
  },
  mi_agenda: {
    key: 'mi_agenda',
    title: 'Mi Agenda',
    description: 'Próximas 5 reuniones, llamadas y citas programadas.',
    category: 'PERSONAL',
    requiredPermissions: ['home:read'],
    suggestedRoles: ['admin', 'comercial', 'gerencia'],
    defaultSize: 'SMALL',
    refreshSeconds: 60,
    dataSource: 'LIVE_LIGHT',
    configSchema: EmptyConfigSchema,
    drillDownRoute: () => '/dashboard/comercial/agenda',
    availableFrom: '15.2',
  },
  mis_anclados: {
    key: 'mis_anclados',
    title: 'Mis Elementos Fijados',
    description: 'Acceso directo a clientes, proyectos y cotizaciones que sigues de cerca.',
    category: 'PERSONAL',
    requiredPermissions: ['home:read'],
    suggestedRoles: ['admin', 'comercial', 'produccion', 'gerencia'],
    defaultSize: 'SMALL',
    refreshSeconds: 0,
    dataSource: 'LIVE_LIGHT',
    configSchema: EmptyConfigSchema,
    drillDownRoute: () => '/',
    availableFrom: '15.2',
  },
  mis_notificaciones: {
    key: 'mis_notificaciones',
    title: 'Notificaciones Recientes',
    description: 'Las 5 notificaciones más recientes sin leer agrupadas por tipo.',
    category: 'PERSONAL',
    requiredPermissions: ['home:read'],
    suggestedRoles: ['admin', 'comercial', 'produccion', 'planta', 'gerencia'],
    defaultSize: 'SMALL',
    refreshSeconds: 30,
    dataSource: 'LIVE_LIGHT',
    configSchema: EmptyConfigSchema,
    drillDownRoute: () => '/dashboard/inbox',
    availableFrom: '15.2',
  },
  atajos: {
    key: 'atajos',
    title: 'Atajos y Acciones Rápidas',
    description: 'Lanzadores rápidos: nueva cotización, cliente, registrar tiempo o proyecto.',
    category: 'PERSONAL',
    requiredPermissions: ['home:read'],
    suggestedRoles: ['admin', 'comercial', 'produccion', 'gerencia'],
    defaultSize: 'SMALL',
    refreshSeconds: 0,
    dataSource: 'LIVE_LIGHT',
    configSchema: EmptyConfigSchema,
    drillDownRoute: () => '/',
    availableFrom: '15.2',
  },

  // ==========================================================================
  // COMERCIALES (requieren opportunity:read o quote:read)
  // ==========================================================================
  meta_ventas: {
    key: 'meta_ventas',
    title: 'Meta de Ventas del Mes',
    description: 'Avance contra la meta mensual con indicador de ritmo y proyección esperada.',
    category: 'COMERCIAL',
    requiredPermissions: ['opportunity:read'],
    suggestedRoles: ['comercial', 'supervisor', 'gerencia', 'admin'],
    defaultSize: 'MEDIUM',
    refreshSeconds: 300,
    dataSource: 'METRIC_DAILY',
    configSchema: EmptyConfigSchema,
    drillDownRoute: () => '/metas',
    availableFrom: '15.2',
  },
  pipeline_resumen: {
    key: 'pipeline_resumen',
    title: 'Resumen del Pipeline',
    description: 'Valor total por etapa, valor ponderado por probabilidad y conteo de tratos.',
    category: 'COMERCIAL',
    requiredPermissions: ['opportunity:read'],
    suggestedRoles: ['comercial', 'supervisor', 'gerencia', 'admin'],
    defaultSize: 'LARGE',
    mobileFallbackKey: 'mis_tareas_resumen',
    refreshSeconds: 300,
    dataSource: 'METRIC_DAILY',
    configSchema: EmptyConfigSchema,
    drillDownRoute: () => '/dashboard/oportunidades',
    availableFrom: '15.2',
  },
  cotizaciones_sin_seguimiento: {
    key: 'cotizaciones_sin_seguimiento',
    title: 'Cotizaciones sin Seguimiento',
    description: 'Cotizaciones enviadas pendientes de contacto, priorizadas por urgencia.',
    category: 'COMERCIAL',
    requiredPermissions: ['quote:read'],
    suggestedRoles: ['comercial', 'supervisor', 'gerencia', 'admin'],
    defaultSize: 'MEDIUM',
    refreshSeconds: 300,
    dataSource: 'METRIC_DAILY',
    configSchema: EmptyConfigSchema,
    drillDownRoute: () => '/dashboard/cotizador',
    availableFrom: '15.2',
  },
  oportunidades_estancadas: {
    key: 'oportunidades_estancadas',
    title: 'Oportunidades Estancadas',
    description: 'Tratos que han superado el tiempo máximo comprometido en su etapa.',
    category: 'COMERCIAL',
    requiredPermissions: ['opportunity:read'],
    suggestedRoles: ['comercial', 'supervisor', 'gerencia', 'admin'],
    defaultSize: 'MEDIUM',
    refreshSeconds: 300,
    dataSource: 'METRIC_DAILY',
    configSchema: EmptyConfigSchema,
    drillDownRoute: () => '/dashboard/oportunidades',
    availableFrom: '15.2',
  },
  clientes_calientes: {
    key: 'clientes_calientes',
    title: 'Clientes de Alta Temperatura',
    description: 'Top 5 cuentas con mayor probabilidad de cierre y razones del algoritmo.',
    category: 'COMERCIAL',
    requiredPermissions: ['client:read'],
    suggestedRoles: ['comercial', 'supervisor', 'gerencia', 'admin'],
    defaultSize: 'MEDIUM',
    refreshSeconds: 300,
    dataSource: 'METRIC_DAILY',
    configSchema: EmptyConfigSchema,
    drillDownRoute: () => '/dashboard/clientes',
    availableFrom: '15.2',
  },
  actividad_semana: {
    key: 'actividad_semana',
    title: 'Actividad Comercial de la Semana',
    description: 'Conteo de llamadas, correos, WhatsApps y visitas efectuadas.',
    category: 'COMERCIAL',
    requiredPermissions: ['opportunity:read'],
    suggestedRoles: ['comercial', 'supervisor', 'gerencia', 'admin'],
    defaultSize: 'MEDIUM',
    refreshSeconds: 300,
    dataSource: 'METRIC_DAILY',
    configSchema: EmptyConfigSchema,
    drillDownRoute: () => '/dashboard/comercial/dashboard',
    availableFrom: '15.2',
  },
  conversion_embudo: {
    key: 'conversion_embudo',
    title: 'Tasa de Conversión del Embudo',
    description: 'Porcentaje de paso entre etapas comerciales en el período seleccionado.',
    category: 'COMERCIAL',
    requiredPermissions: ['opportunity:read'],
    suggestedRoles: ['supervisor', 'gerencia', 'admin'],
    defaultSize: 'MEDIUM',
    refreshSeconds: 300,
    dataSource: 'METRIC_MONTHLY',
    configSchema: EmptyConfigSchema,
    drillDownRoute: () => '/dashboard/comercial/dashboard',
    availableFrom: '15.2',
  },

  // ==========================================================================
  // PRODUCCIÓN (requieren production:read)
  // ==========================================================================
  proyectos_en_mi_etapa: {
    key: 'proyectos_en_mi_etapa',
    title: 'Proyectos en Mi Etapa',
    description: 'Órdenes de producción que esperan acción o aprobación de este usuario.',
    category: 'PRODUCCION',
    requiredPermissions: ['production:read'],
    suggestedRoles: ['produccion', 'planta', 'admin'],
    defaultSize: 'MEDIUM',
    refreshSeconds: 120,
    dataSource: 'LIVE_LIGHT',
    configSchema: EmptyConfigSchema,
    drillDownRoute: () => '/dashboard/produccion',
    availableFrom: '15.2',
  },
  proyectos_en_riesgo: {
    key: 'proyectos_en_riesgo',
    title: 'Proyectos en Riesgo',
    description: 'Trabajos retrasados o con fecha límite próxima ordenados por criticidad.',
    category: 'PRODUCCION',
    requiredPermissions: ['production:read'],
    suggestedRoles: ['produccion', 'planta', 'gerencia', 'admin'],
    defaultSize: 'MEDIUM',
    refreshSeconds: 300,
    dataSource: 'METRIC_DAILY',
    configSchema: EmptyConfigSchema,
    drillDownRoute: () => '/dashboard/produccion',
    availableFrom: '15.2',
  },
  capacidad_planta: {
    key: 'capacidad_planta',
    title: 'Capacidad y Utilización de Planta',
    description: 'Utilización por máquina de la semana, con el cuello de botella identificado.',
    category: 'PRODUCCION',
    requiredPermissions: ['production:read'],
    suggestedRoles: ['produccion', 'planta', 'gerencia', 'admin'],
    defaultSize: 'LARGE',
    mobileFallbackKey: 'proyectos_en_mi_etapa',
    refreshSeconds: 300,
    dataSource: 'METRIC_DAILY',
    configSchema: EmptyConfigSchema,
    drillDownRoute: () => '/dashboard/produccion/capacidad',
    availableFrom: '15.2',
  },
  calidad_pendiente: {
    key: 'calidad_pendiente',
    title: 'Aprobaciones de Calidad Pendientes',
    description: 'Inspecciones y vistos buenos de control de calidad esperando dictamen.',
    category: 'PRODUCCION',
    requiredPermissions: ['production:read'],
    suggestedRoles: ['produccion', 'planta', 'admin'],
    defaultSize: 'SMALL',
    refreshSeconds: 180,
    dataSource: 'LIVE_LIGHT',
    configSchema: EmptyConfigSchema,
    drillDownRoute: () => '/dashboard/produccion',
    availableFrom: '15.2',
  },
  desperdicio_semana: {
    key: 'desperdicio_semana',
    title: 'Desperdicio de Materiales',
    description: 'Merma real observada contra la tolerancia calculada por la fórmula.',
    category: 'PRODUCCION',
    requiredPermissions: ['production:read'],
    suggestedRoles: ['produccion', 'planta', 'gerencia', 'admin'],
    defaultSize: 'SMALL',
    refreshSeconds: 300,
    dataSource: 'METRIC_DAILY',
    configSchema: EmptyConfigSchema,
    drillDownRoute: () => '/dashboard/produccion/costos',
    availableFrom: '15.2',
  },
  entregas_hoy: {
    key: 'entregas_hoy',
    title: 'Entregas y Despachos de Hoy',
    description: 'Remisiones y pedidos con compromiso de entrega programado para hoy.',
    category: 'PRODUCCION',
    requiredPermissions: ['production:read'],
    suggestedRoles: ['produccion', 'planta', 'comercial', 'admin'],
    defaultSize: 'SMALL',
    refreshSeconds: 120,
    dataSource: 'LIVE_LIGHT',
    configSchema: EmptyConfigSchema,
    drillDownRoute: () => '/dashboard/produccion',
    availableFrom: '15.2',
  },

  // ==========================================================================
  // FINANCIEROS (requieren cost:read — sin ese permiso el servidor NO los envía)
  // ==========================================================================
  margen_real_mes: {
    key: 'margen_real_mes',
    title: 'Margen Real del Mes',
    description: 'Margen real acumulado contra el margen cotizado y su porcentaje de desviación.',
    category: 'FINANCIERO',
    requiredPermissions: ['cost:read'],
    suggestedRoles: ['gerencia', 'admin'],
    defaultSize: 'MEDIUM',
    refreshSeconds: 300,
    dataSource: 'METRIC_MONTHLY',
    configSchema: EmptyConfigSchema,
    drillDownRoute: () => '/dashboard/produccion/costos',
    availableFrom: '15.2',
  },
  proyectos_sin_costos: {
    key: 'proyectos_sin_costos',
    title: 'Proyectos sin Costeo Real',
    description: 'Alerta permanente de órdenes entregadas o cerradas sin mano de obra ni insumos asentados.',
    category: 'FINANCIERO',
    requiredPermissions: ['cost:read'],
    suggestedRoles: ['gerencia', 'admin'],
    defaultSize: 'SMALL',
    refreshSeconds: 300,
    dataSource: 'METRIC_DAILY',
    configSchema: EmptyConfigSchema,
    drillDownRoute: () => '/dashboard/produccion/costos',
    availableFrom: '15.2',
  },
  rentabilidad_clientes: {
    key: 'rentabilidad_clientes',
    title: 'Rentabilidad por Cliente',
    description: 'Top 5 cuentas con mayor y menor rentabilidad porcentual en el período.',
    category: 'FINANCIERO',
    requiredPermissions: ['cost:read'],
    suggestedRoles: ['gerencia', 'admin'],
    defaultSize: 'MEDIUM',
    refreshSeconds: 300,
    dataSource: 'METRIC_MONTHLY',
    configSchema: EmptyConfigSchema,
    drillDownRoute: () => '/dashboard/produccion/costos',
    availableFrom: '15.2',
  },

  // ==========================================================================
  // SISTEMA
  // ==========================================================================
  alertas_criticas: {
    key: 'alertas_criticas',
    title: 'Alertas Críticas del Sistema',
    description: 'Incidencias graves y alertas operativas que requieren acción inmediata.',
    category: 'SISTEMA',
    requiredPermissions: ['admin:access'],
    suggestedRoles: ['admin'],
    defaultSize: 'SMALL',
    refreshSeconds: 60,
    dataSource: 'LIVE_LIGHT',
    configSchema: EmptyConfigSchema,
    drillDownRoute: () => '/dashboard/admin/salud',
    availableFrom: '15.2',
  },
  calidad_datos: {
    key: 'calidad_datos',
    title: 'Calidad de Datos e Incidencias',
    description: 'Anomalías detectadas en clientes, identificaciones y registros huérfanos.',
    category: 'SISTEMA',
    requiredPermissions: ['admin:access'],
    suggestedRoles: ['admin'],
    defaultSize: 'SMALL',
    refreshSeconds: 300,
    dataSource: 'METRIC_DAILY',
    configSchema: EmptyConfigSchema,
    drillDownRoute: () => '/dashboard/compliance',
    availableFrom: '15.2',
  },
  salud_integraciones: {
    key: 'salud_integraciones',
    title: 'Salud de Integraciones',
    description: 'Estado de conectividad y pulso activo de Meta, WhatsApp, Drive y Odoo.',
    category: 'SISTEMA',
    requiredPermissions: ['admin:access'],
    suggestedRoles: ['admin'],
    defaultSize: 'MEDIUM',
    refreshSeconds: 60,
    dataSource: 'LIVE_LIGHT',
    configSchema: EmptyConfigSchema,
    drillDownRoute: () => '/dashboard/admin/integraciones',
    availableFrom: '15.2',
  },

  // ==========================================================================
  // WIDGETS DECLARADOS PERO NO IMPLEMENTADOS AQUÍ (disponibles en próximas etapas)
  // ==========================================================================
  cumplimiento_tareas: {
    key: 'cumplimiento_tareas',
    title: 'Cumplimiento Individual de Tareas',
    description: 'Porcentaje de tareas completadas a tiempo en los últimos 30 días.',
    category: 'EQUIPO',
    requiredPermissions: ['performance:read_own'],
    suggestedRoles: ['admin', 'comercial', 'produccion', 'planta', 'gerencia'],
    defaultSize: 'SMALL',
    refreshSeconds: 300,
    dataSource: 'METRIC_DAILY',
    configSchema: EmptyConfigSchema,
    drillDownRoute: () => '/mi-rendimiento',
    availableFrom: '15.3',
  },
  mi_capacidad: {
    key: 'mi_capacidad',
    title: 'Mi Utilización y Horas',
    description: 'Horas disponibles, registradas y desvío respecto a la jornada laboral.',
    category: 'EQUIPO',
    requiredPermissions: ['performance:read_own'],
    suggestedRoles: ['admin', 'comercial', 'produccion', 'planta'],
    defaultSize: 'SMALL',
    refreshSeconds: 300,
    dataSource: 'METRIC_DAILY',
    configSchema: EmptyConfigSchema,
    drillDownRoute: () => '/mi-rendimiento',
    availableFrom: '15.3',
  },
  cumplimiento_equipo: {
    key: 'cumplimiento_equipo',
    title: 'Cumplimiento del Equipo',
    description: 'Tasa comparativa de cumplimiento y tareas en riesgo de los miembros del área.',
    category: 'EQUIPO',
    requiredPermissions: ['performance:read_team'],
    suggestedRoles: ['supervisor', 'gerencia', 'admin'],
    defaultSize: 'MEDIUM',
    refreshSeconds: 300,
    dataSource: 'METRIC_DAILY',
    configSchema: EmptyConfigSchema,
    drillDownRoute: () => '/equipo/rendimiento',
    availableFrom: '15.3',
  },
  tablero_anuncios: {
    key: 'tablero_anuncios',
    title: 'Últimos Anuncios',
    description: 'Comunicados y directivas oficiales recientes para la empresa o área.',
    category: 'EQUIPO',
    requiredPermissions: ['announcement:read'],
    suggestedRoles: ['admin', 'comercial', 'produccion', 'planta', 'gerencia'],
    defaultSize: 'MEDIUM',
    refreshSeconds: 120,
    dataSource: 'LIVE_LIGHT',
    configSchema: EmptyConfigSchema,
    drillDownRoute: () => '/anuncios',
    availableFrom: '15.4',
  },
  anuncios_sin_confirmar: {
    key: 'anuncios_sin_confirmar',
    title: 'Anuncios Pendientes de Acuse',
    description: 'Comunicados de lectura obligatoria que no has confirmado aún.',
    category: 'EQUIPO',
    requiredPermissions: ['announcement:read'],
    suggestedRoles: ['admin', 'comercial', 'produccion', 'planta', 'gerencia'],
    defaultSize: 'SMALL',
    refreshSeconds: 120,
    dataSource: 'LIVE_LIGHT',
    configSchema: EmptyConfigSchema,
    drillDownRoute: () => '/anuncios',
    availableFrom: '15.4',
  },
  reconocimientos: {
    key: 'reconocimientos',
    title: 'Muro de Reconocimientos',
    description: 'Agradecimientos, felicitaciones y medallas otorgadas entre compañeros.',
    category: 'EQUIPO',
    requiredPermissions: ['announcement:read'],
    suggestedRoles: ['admin', 'comercial', 'produccion', 'planta', 'gerencia'],
    defaultSize: 'MEDIUM',
    refreshSeconds: 180,
    dataSource: 'LIVE_LIGHT',
    configSchema: EmptyConfigSchema,
    drillDownRoute: () => '/anuncios',
    availableFrom: '15.4',
  },
  mis_menciones: {
    key: 'mis_menciones',
    title: 'Menciones sin Leer en Chat',
    description: 'Canales y mensajes directos donde fuiste mencionado recientemente.',
    category: 'EQUIPO',
    requiredPermissions: ['chat:read'],
    suggestedRoles: ['admin', 'comercial', 'produccion', 'planta', 'gerencia'],
    defaultSize: 'SMALL',
    refreshSeconds: 30,
    dataSource: 'LIVE_LIGHT',
    configSchema: EmptyConfigSchema,
    drillDownRoute: () => '/chat',
    availableFrom: '15.5',
  },
  equipo_presencia: {
    key: 'equipo_presencia',
    title: 'Presencia del Equipo',
    description: 'Quién está conectado en línea, en llamada o ausente en tiempo real.',
    category: 'EQUIPO',
    requiredPermissions: ['chat:read'],
    suggestedRoles: ['admin', 'comercial', 'produccion', 'planta', 'gerencia'],
    defaultSize: 'SMALL',
    refreshSeconds: 30,
    dataSource: 'LIVE_LIGHT',
    configSchema: EmptyConfigSchema,
    drillDownRoute: () => '/chat',
    availableFrom: '15.5',
  },
};

/**
 * Retorna todos los widgets declarados en el catálogo.
 */
export function getAllWidgets(): WidgetDefinition[] {
  return Object.values(WIDGET_CATALOG);
}

/**
 * Retorna si un widget está disponible funcionalmente en la versión actual (15.5).
 */
export function isWidgetAvailable(widget: WidgetDefinition, currentStage = '15.5'): boolean {
  return widget.availableFrom <= currentStage;
}
